In [1]:
import pandas as pd
from IPython.display import display

df = pd.read_excel('OrderHistory.xlsx')
cleanDf = pd.DataFrame()
cleanFilledDf = pd.DataFrame()

# Clean the data
for index, row in df.iterrows():
    if row['Pair'].isalpha() and row['Pair'] != 'Date':
        cleanDf = cleanDf.append(row)
        if row['status'] == 'Filled':
            cleanFilledDf = cleanFilledDf.append(row)
        

groupDf = cleanDf.groupby('Pair')
cleanFilledDf = cleanFilledDf.groupby('Pair')

for name, group in cleanFilledDf:
    display(group)

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
17,0.00002738,2018-03-01 23:26:16,351.0,351.0,0.00002742,ADABTC,0.009610,BUY,Filled
37,0.00002799,2018-03-01 14:34:14,344.0,344.0,0.00002799,ADABTC,0.009629,SELL,Filled
86,0.00002862,2018-03-01 01:36:22,344.0,344.0,0.00002867,ADABTC,0.009845,BUY,Filled
143,0.00002928,2018-02-28 13:20:31,315.0,315.0,0.00002928,ADABTC,0.009223,SELL,Filled
552,0.00003076,2018-02-24 15:53:28,315.0,315.0,0.00003077,ADABTC,0.009689,BUY,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
126,0.00326,2018-02-28 16:19:33,10.139,10.139,0.00326,BCDBTC,0.033054,BUY,Filled
247,0.003406,2018-02-27 19:21:03,9.837,9.837,0.003405,BCDBTC,0.033495,SELL,Filled
295,0.003549,2018-02-27 04:48:30,9.837,9.837,0.003548,BCDBTC,0.034902,BUY,Filled
349,0.003632,2018-02-26 20:10:33,9.746,9.746,0.003632,BCDBTC,0.035398,SELL,Filled
402,0.003932,2018-02-26 07:25:38,9.746,9.746,0.003935,BCDBTC,0.038312,BUY,Filled
416,0.00405,2018-02-26 05:06:19,9.719,9.719,0.00404,BCDBTC,0.039362,SELL,Filled
424,0.004046,2018-02-26 05:01:01,9.719,9.719,0.004046,BCDBTC,0.039324,BUY,Filled
468,0.004182,2018-02-26 04:51:37,9.246,9.246,0.004181,BCDBTC,0.038667,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
214,0.0010137,2018-02-28 05:06:07,5.0,5.0,0.0010137,BNBBTC,0.005069,BUY,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
11,0.010334,2018-03-01 23:43:43,4.00,4.0,0.010334,BTGBTC,0.041336,BUY,Filled
130,0.010613,2018-02-28 16:08:16,3.93,3.93,0.010613,BTGBTC,0.041710,SELL,Filled
217,0.010907,2018-02-28 04:21:51,3.93,3.93,0.010907,BTGBTC,0.042865,BUY,Filled
316,0.011143,2018-02-27 00:54:34,3.75,3.75,0.011143,BTGBTC,0.041787,SELL,Filled
481,0.011445,2018-02-25 14:27:21,3.75,3.75,0.011445,BTGBTC,0.042919,BUY,Filled
545,0.011731,2018-02-25 00:36:18,3.66,3.66,0.011731,BTGBTC,0.042936,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
191,0.00002033,2018-02-28 05:44:54,1230.0,1230.0,0.00002033,BTSBTC,0.025006,BUY,Filled
541,0.00002137,2018-02-25 00:36:28,1652.0,1652.0,0.00002137,BTSBTC,0.035303,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
70,0.00001119,2018-03-01 06:34:24,1586.0,1586.0,0.00001119,CNDBTC,0.017747,BUY,Filled
80,0.00001148,2018-03-01 02:25:13,1477.0,1477.0,0.00001148,CNDBTC,0.016956,SELL,Filled
538,0.00001422,2018-02-25 00:36:36,1923.0,1923.0,0.00001422,CNDBTC,0.027345,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
471,0.00079505,2018-02-26 02:35:03,18.0,18.0,0.00079505,EOSBTC,0.014311,BUY,Filled
535,0.00081209,2018-02-25 00:36:45,18.0,18.0,0.00081203,EOSBTC,0.014618,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
115,0.00315,2018-02-28 18:03:07,11.55,11.55,0.00315,ETCBTC,0.036383,BUY,Filled
118,0.003215,2018-02-28 17:17:59,11.41,11.41,0.003215,ETCBTC,0.036684,SELL,Filled
264,0.003293,2018-02-27 14:01:20,11.41,11.41,0.003293,ETCBTC,0.037574,BUY,Filled
278,0.00338,2018-02-27 09:32:02,11.36,11.36,0.003379,ETCBTC,0.038397,SELL,Filled
371,0.003483,2018-02-26 13:24:50,11.36,11.36,0.003484,ETCBTC,0.039567,BUY,Filled
463,0.00358,2018-02-26 04:52:27,10.10,10.1,0.003578,ETCBTC,0.036157,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
184,0.080492,2018-02-28 06:18:56,0.416,0.416,0.080533,ETHBTC,0.033485,BUY,Filled
224,0.082284,2018-02-28 00:16:15,0.410,0.41,0.082276,ETHBTC,0.033737,SELL,Filled
269,0.082752,2018-02-27 11:00:23,0.410,0.41,0.082756,ETHBTC,0.033929,BUY,Filled
310,0.0845,2018-02-27 01:33:38,0.408,0.408,0.0845,ETHBTC,0.034476,SELL,Filled
367,0.086109,2018-02-26 13:26:59,0.408,0.408,0.08612,ETHBTC,0.035133,BUY,Filled
458,0.088511,2018-02-26 04:52:37,0.302,0.302,0.088458,ETHBTC,0.026731,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
21,0.000868,2018-03-01 19:33:51,29.15,29.15,0.000868,HSRBTC,0.025303,SELL,Filled
122,0.000895,2018-02-28 17:01:22,29.15,29.15,0.000895,HSRBTC,0.026090,BUY,Filled
234,0.000918,2018-02-27 22:06:18,28.63,28.63,0.000918,HSRBTC,0.026283,SELL,Filled
330,0.000932,2018-02-26 21:44:35,28.63,28.63,0.000932,HSRBTC,0.026684,BUY,Filled
455,0.000954,2018-02-26 04:52:59,18.37,18.37,0.000954,HSRBTC,0.017525,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
146,0.34801,2018-02-28 13:02:53,7.18,7.18,0.34801,ICXBNB,2.49872,BUY,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
549,0.00018236,2018-02-25 00:35:55,158.0,158.0,0.00018236,IOTABTC,0.028813,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
7,0.019082,2018-03-02 00:36:43,1.80,1.8,0.019084,LTCBTC,0.034348,BUY,Filled
67,0.019486,2018-03-01 06:46:45,1.79,1.79,0.019486,LTCBTC,0.034880,SELL,Filled
175,0.01975,2018-02-28 06:35:57,1.79,1.79,0.019757,LTCBTC,0.035353,BUY,Filled
239,0.020214,2018-02-27 20:00:43,1.78,1.78,0.020214,LTCBTC,0.035981,SELL,Filled
288,0.020821,2018-02-27 08:26:08,1.78,1.78,0.020823,LTCBTC,0.037062,BUY,Filled
327,0.02128,2018-02-26 21:50:11,1.58,1.58,0.02128,LTCBTC,0.033623,SELL,Filled
474,0.023595,2018-02-26 02:19:57,1.58,1.58,0.023659,LTCBTC,0.037281,BUY,Filled
529,0.02117,2018-02-25 00:37:27,1.76,1.76,0.02117,LTCBTC,0.037260,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
300,0.0018904,2018-02-27 03:50:07,64.55,64.55,0.0018907,LUNBTC,0.122019,BUY,Filled
323,0.0019816,2018-02-26 23:17:32,64.44,64.44,0.0019811,LUNBTC,0.127694,SELL,Filled
386,0.0020595,2018-02-26 11:49:18,64.44,64.44,0.0020594,LUNBTC,0.132708,BUY,Filled
452,0.0021091,2018-02-26 04:53:20,45.84,45.84,0.0021091,LUNBTC,0.096681,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
525,0.000709,2018-02-25 00:37:45,32.42,32.42,0.000709,MCOBTC,0.022986,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
40,0.011849,2018-03-01 13:27:50,1.77,1.77,0.01185,NEOBTC,0.020973,BUY,Filled
44,0.012195,2018-03-01 10:47:49,1.74,1.74,0.012194,NEOBTC,0.021218,SELL,Filled
360,0.012833,2018-02-26 14:20:42,1.74,1.74,0.01284,NEOBTC,0.022330,BUY,Filled
383,0.013154,2018-02-26 12:16:16,1.54,1.54,0.013151,NEOBTC,0.020258,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
521,0.001694,2018-02-25 00:38:00,22.75,22.75,0.001693,OMGBTC,0.038539,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
172,0.00005432,2018-02-28 06:36:47,597.0,597.0,0.00005434,POWRBTC,0.032429,BUY,Filled
251,0.00005585,2018-02-27 19:01:28,589.0,589.0,0.00005583,POWRBTC,0.032896,SELL,Filled
292,0.00005795,2018-02-27 05:28:44,589.0,589.0,0.00005795,POWRBTC,0.034133,BUY,Filled
313,0.0000592,2018-02-27 01:18:33,586.0,586.0,0.0000592,POWRBTC,0.034691,SELL,Filled
399,0.00006004,2018-02-26 09:10:02,586.0,586.0,0.00006004,POWRBTC,0.035183,BUY,Filled
428,0.00006132,2018-02-26 04:59:26,398.0,398.0,0.00006132,POWRBTC,0.024405,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
31,0.002412,2018-03-01 18:37:13,16.05,16.05,0.002412,QTUMBTC,0.038713,BUY,Filled
106,0.002466,2018-02-28 19:12:12,15.83,15.83,0.002465,QTUMBTC,0.039037,SELL,Filled
195,0.002515,2018-02-28 05:35:49,15.83,15.83,0.002516,QTUMBTC,0.039813,BUY,Filled
420,0.002583,2018-02-26 05:03:27,11.64,11.64,0.002583,QTUMBTC,0.030067,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
27,0.00025248,2018-03-01 18:43:03,121.0,121.0,0.0002526,RDNBTC,0.030550,BUY,Filled
89,0.0002594,2018-03-01 00:49:21,118.0,118.0,0.00025939,RDNBTC,0.030609,SELL,Filled
221,0.00028529,2018-02-28 00:34:21,118.0,118.0,0.00028529,RDNBTC,0.033664,BUY,Filled
274,0.00029143,2018-02-27 10:23:26,117.0,117.0,0.00029143,RDNBTC,0.034097,SELL,Filled
392,0.0003038,2018-02-26 11:11:11,117.0,117.0,0.00030388,RDNBTC,0.035545,BUY,Filled
447,0.00031231,2018-02-26 04:54:23,97.0,97.0,0.00031227,RDNBTC,0.030294,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
261,0.00002831,2018-02-27 15:12:52,699.0,699.0,0.00002831,REQBTC,0.019789,BUY,Filled
320,0.00002902,2018-02-26 23:47:37,652.0,652.0,0.00002902,REQBTC,0.018921,SELL,Filled
380,0.00003068,2018-02-26 12:29:42,652.0,652.0,0.00003068,REQBTC,0.020003,BUY,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
53,0.00001439,2018-03-01 08:08:20,1157.0,1157.0,0.0000144,SNTBTC,0.016649,BUY,Filled
83,0.00001477,2018-03-01 02:21:49,1080.0,1080.0,0.00001477,SNTBTC,0.015952,SELL,Filled
514,0.00001687,2018-02-25 00:38:37,1208.0,1208.0,0.00001687,SNTBTC,0.020379,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
75,0.000696,2018-03-01 03:12:33,57.69,57.69,0.000696,STRATBTC,0.040137,BUY,Filled
135,0.000712,2018-02-28 15:54:12,57.20,57.2,0.000712,STRATBTC,0.040727,SELL,Filled
389,0.000728,2018-02-26 11:11:30,57.20,57.2,0.000728,STRATBTC,0.041642,BUY,Filled
444,0.000743,2018-02-26 04:54:41,36.06,36.06,0.000743,STRATBTC,0.026793,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
510,0.00005298,2018-02-25 00:38:54,412.0,412.0,0.00005298,SUBBTC,0.021828,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
281,0.00000396,2018-02-27 09:18:08,45103.0,45103.0,0.00000396,TRXBTC,0.178608,BUY,Filled
337,0.00000405,2018-02-26 21:31:52,45077.0,45077.0,0.00000405,TRXBTC,0.182562,SELL,Filled
377,0.00000407,2018-02-26 12:56:43,45077.0,45077.0,0.00000407,TRXBTC,0.183463,BUY,Filled
405,0.00000416,2018-02-26 05:35:48,24476.0,24476.0,0.00000416,TRXBTC,0.101820,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
95,0.0004394,2018-03-01 00:33:32,63.0,63.0,0.00043939,VENBTC,0.027682,SELL,Filled
152,0.00047523,2018-02-28 06:48:38,63.0,63.0,0.00047523,VENBTC,0.029939,BUY,Filled
242,0.00049012,2018-02-27 19:51:49,61.0,61.0,0.00049007,VENBTC,0.029897,SELL,Filled
333,0.0005345,2018-02-26 21:41:08,61.0,61.0,0.0005345,VENBTC,0.032605,BUY,Filled
346,0.00054778,2018-02-26 20:46:24,55.0,55.0,0.000547,VENBTC,0.030128,SELL,Filled
477,0.00059867,2018-02-25 15:45:55,55.0,55.0,0.00059994,VENBTC,0.032927,BUY,Filled
484,0.00061279,2018-02-25 14:25:13,54.0,54.0,0.0006126,VENBTC,0.033090,SELL,Filled
488,0.00061499,2018-02-25 14:20:17,54.0,54.0,0.00061654,VENBTC,0.033209,BUY,Filled
507,0.000574,2018-02-25 00:39:02,58.0,58.0,0.000574,VENBTC,0.033292,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
92,0.00003676,2018-03-01 00:45:46,499.0,499.0,0.00003676,VIBEBTC,0.018343,BUY,Filled
178,0.00003755,2018-02-28 06:33:16,461.0,461.0,0.00003753,VIBEBTC,0.017311,SELL,Filled
395,0.00004334,2018-02-26 09:23:01,461.0,461.0,0.00004334,VIBEBTC,0.019980,BUY,Filled
492,0.00004337,2018-02-25 00:40:12,914.0,914.0,0.00004336,VIBEBTC,0.039640,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
187,0.000597,2018-02-28 06:04:49,58.63,58.63,0.000597,WAVESBTC,0.034996,BUY,Filled
504,0.000674,2018-02-25 00:39:12,19.34,19.34,0.000674,WAVESBTC,0.013035,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
24,0.0017244,2018-03-01 19:01:29,11.45,11.45,0.0017244,WTCBTC,0.019744,BUY,Filled
61,0.0017733,2018-03-01 07:07:06,9.94,9.94,0.0017732,WTCBTC,0.017626,SELL,Filled
207,0.0020115,2018-02-28 05:08:00,9.94,9.94,0.0020115,WTCBTC,0.019994,BUY,Filled
501,0.0021759,2018-02-25 00:39:20,6.71,6.71,0.0021758,WTCBTC,0.014600,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
0,0.00003049,2018-03-02 00:56:15,1154.0,1154.0,0.00003049,XLMBTC,0.035185,BUY,Filled
48,0.00003115,2018-03-01 10:20:59,1139.0,1139.0,0.00003114,XLMBTC,0.035477,SELL,Filled
199,0.00003267,2018-02-28 05:25:53,1139.0,1139.0,0.00003267,XLMBTC,0.037211,BUY,Filled
254,0.00003338,2018-02-27 18:04:11,1134.0,1134.0,0.00003338,XLMBTC,0.037853,SELL,Filled
353,0.00003495,2018-02-26 19:08:36,1134.0,1134.0,0.00003495,XLMBTC,0.039633,BUY,Filled
441,0.00003568,2018-02-26 04:55:32,873.0,873.0,0.00003568,XLMBTC,0.031149,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
436,0.028408,2018-02-26 04:55:42,0.704,0.704,0.028408,XMRBTC,0.02,BUY,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
204,0.00008575,2018-02-28 05:16:05,389.0,389.0,0.00008575,XRPBTC,0.033357,BUY,Filled
258,0.00008768,2018-02-27 17:30:46,388.0,388.0,0.00008768,XRPBTC,0.034020,SELL,Filled
356,0.00009073,2018-02-26 16:15:14,388.0,388.0,0.00009073,XRPBTC,0.035202,BUY,Filled
433,0.0000928,2018-02-26 04:55:55,286.0,286.0,0.0000928,XRPBTC,0.026541,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
98,0.00000517,2018-03-01 00:23:12,6729.0,6729.0,0.00000517,XVGBTC,0.034776,BUY,Filled
111,0.00000529,2018-02-28 18:50:52,6352.0,6352.0,0.00000529,XVGBTC,0.033602,SELL,Filled
162,0.00000551,2018-02-28 06:38:43,6352.0,6352.0,0.00000551,XVGBTC,0.035000,BUY,Filled
496,0.00000589,2018-02-25 00:39:53,4878.0,4878.0,0.00000589,XVGBTC,0.028731,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
140,0.03689,2018-02-28 15:15:20,0.892,0.892,0.03689,ZECBTC,0.032906,SELL,Filled
231,0.038205,2018-02-27 23:41:43,0.892,0.892,0.038204,ZECBTC,0.034078,BUY,Filled
284,0.039002,2018-02-27 08:50:39,0.886,0.886,0.039001,ZECBTC,0.034555,SELL,Filled
363,0.039842,2018-02-26 14:12:31,0.886,0.886,0.039842,ZECBTC,0.035301,BUY,Filled
411,0.040703,2018-02-26 05:16:54,0.634,0.634,0.040703,ZECBTC,0.025806,SELL,Filled

In [2]:
  for name, group in groupDf:
    display(group)

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
17,0.00002738,2018-03-01 23:26:16,351.0,351.0,0.00002742,ADABTC,0.009610,BUY,Filled
37,0.00002799,2018-03-01 14:34:14,344.0,344.0,0.00002799,ADABTC,0.009629,SELL,Filled
86,0.00002862,2018-03-01 01:36:22,344.0,344.0,0.00002867,ADABTC,0.009845,BUY,Filled
143,0.00002928,2018-02-28 13:20:31,315.0,315.0,0.00002928,ADABTC,0.009223,SELL,Filled
552,0.00003076,2018-02-24 15:53:28,315.0,315.0,0.00003077,ADABTC,0.009689,BUY,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
126,0.00326,2018-02-28 16:19:33,10.139,10.139,0.00326,BCDBTC,0.033054,BUY,Filled
129,0.0,2018-02-28 16:13:52,0.000,10.108,0.003286,BCDBTC,0.000000,BUY,Expired
138,0.0,2018-02-28 15:28:23,0.000,10.079,0.003304,BCDBTC,0.000000,BUY,Expired
139,0.0,2018-02-28 15:22:35,0.000,10.052,0.003317,BCDBTC,0.000000,BUY,Expired
247,0.003406,2018-02-27 19:21:03,9.837,9.837,0.003405,BCDBTC,0.033495,SELL,Filled
250,0.0,2018-02-27 19:15:37,0.000,9.837,0.003412,BCDBTC,0.000000,SELL,Expired
295,0.003549,2018-02-27 04:48:30,9.837,9.837,0.003548,BCDBTC,0.034902,BUY,Filled
298,0.0,2018-02-27 04:43:03,0.000,9.823,0.00355,BCDBTC,0.000000,BUY,Expired
307,0.0,2018-02-27 03:42:59,0.000,9.809,0.003552,BCDBTC,0.000000,BUY,Expired
308,0.0,2018-02-27 03:37:33,0.000,9.795,0.00355,BCDBTC,0.000000,BUY,Expired
349,0.003632,2018-02-26 20:10:33,9.746,9.746,0.003632,BCDBTC,0.035398,SELL,Filled
352,0.0,2018-02-26 20:05:09,0.000,9.746,0.003627,BCDBTC,0.000000,SELL,Expired
402,0.003932,2018-02-26 07:25:38,9.746,9.746,0.003935,BCDBTC,0.038312,BUY,Filled
416,0.00405,2018-02-26 05:06:19,9.719,9.719,0.00404,BCDBTC,0.039362,SELL,Filled
424,0.004046,2018-02-26 05:01:01,9.719,9.719,0.004046,BCDBTC,0.039324,BUY,Filled
431,0.0,2018-02-26 04:57:05,0.000,9.707,0.004093,BCDBTC,0.000000,BUY,Expired
468,0.004182,2018-02-26 04:51:37,9.246,9.246,0.004181,BCDBTC,0.038667,SELL,Filled
548,0.0,2018-02-25 00:36:10,0.000,9.246,0.003705,BCDBTC,0.000000,SELL,Expired

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
214,0.0010137,2018-02-28 05:06:07,5.0,5.0,0.0010137,BNBBTC,0.005069,BUY,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
11,0.010334,2018-03-01 23:43:43,4.00,4.0,0.010334,BTGBTC,0.041336,BUY,Filled
14,0.0,2018-03-01 23:38:09,0.00,3.99,0.010372,BTGBTC,0.000000,BUY,Expired
15,0.0,2018-03-01 23:32:25,0.00,3.98,0.010384,BTGBTC,0.000000,BUY,Expired
16,0.0,2018-03-01 23:26:34,0.00,3.97,0.010382,BTGBTC,0.000000,BUY,Expired
130,0.010613,2018-02-28 16:08:16,3.93,3.93,0.010613,BTGBTC,0.041710,SELL,Filled
134,0.0,2018-02-28 16:02:24,0.00,3.93,0.010629,BTGBTC,0.000000,SELL,Expired
217,0.010907,2018-02-28 04:21:51,3.93,3.93,0.010907,BTGBTC,0.042865,BUY,Filled
220,0.0,2018-02-28 04:16:27,0.00,3.92,0.01092,BTGBTC,0.000000,BUY,Expired
316,0.011143,2018-02-27 00:54:34,3.75,3.75,0.011143,BTGBTC,0.041787,SELL,Filled
319,0.0,2018-02-27 00:48:20,0.00,3.75,0.011127,BTGBTC,0.000000,SELL,Expired
481,0.011445,2018-02-25 14:27:21,3.75,3.75,0.011445,BTGBTC,0.042919,BUY,Filled
545,0.011731,2018-02-25 00:36:18,3.66,3.66,0.011731,BTGBTC,0.042936,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
191,0.00002033,2018-02-28 05:44:54,1230.0,1230.0,0.00002033,BTSBTC,0.025006,BUY,Filled
541,0.00002137,2018-02-25 00:36:28,1652.0,1652.0,0.00002137,BTSBTC,0.035303,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
70,0.00001119,2018-03-01 06:34:24,1586.0,1586.0,0.00001119,CNDBTC,0.017747,BUY,Filled
80,0.00001148,2018-03-01 02:25:13,1477.0,1477.0,0.00001148,CNDBTC,0.016956,SELL,Filled
103,0.0,2018-03-01 00:02:54,0.0,1477.0,0.00001174,CNDBTC,0.000000,SELL,Expired
158,0.00001233,2018-02-28 06:40:36,1477.0,2839.0,0.00001233,CNDBTC,0.018211,BUY,Partial Fill
538,0.00001422,2018-02-25 00:36:36,1923.0,1923.0,0.00001422,CNDBTC,0.027345,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
20,0.0,2018-03-01 22:18:25,0.0,18.0,0.00076397,EOSBTC,0.000000,SELL,Expired
471,0.00079505,2018-02-26 02:35:03,18.0,18.0,0.00079505,EOSBTC,0.014311,BUY,Filled
535,0.00081209,2018-02-25 00:36:45,18.0,18.0,0.00081203,EOSBTC,0.014618,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
115,0.00315,2018-02-28 18:03:07,11.55,11.55,0.00315,ETCBTC,0.036383,BUY,Filled
118,0.003215,2018-02-28 17:17:59,11.41,11.41,0.003215,ETCBTC,0.036684,SELL,Filled
264,0.003293,2018-02-27 14:01:20,11.41,11.41,0.003293,ETCBTC,0.037574,BUY,Filled
267,0.0,2018-02-27 13:55:27,0.00,11.4,0.003289,ETCBTC,0.000000,BUY,Expired
278,0.00338,2018-02-27 09:32:02,11.36,11.36,0.003379,ETCBTC,0.038397,SELL,Filled
371,0.003483,2018-02-26 13:24:50,11.36,11.36,0.003484,ETCBTC,0.039567,BUY,Filled
375,0.0,2018-02-26 13:19:26,0.00,11.35,0.0035,ETCBTC,0.000000,BUY,Expired
376,0.0,2018-02-26 12:58:04,0.00,11.33,0.003505,ETCBTC,0.000000,BUY,Expired
463,0.00358,2018-02-26 04:52:27,10.10,10.1,0.003578,ETCBTC,0.036157,SELL,Filled
534,0.0,2018-02-25 00:36:53,0.00,10.1,0.003746,ETCBTC,0.000000,SELL,Expired

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
184,0.080492,2018-02-28 06:18:56,0.416,0.416,0.080533,ETHBTC,0.033485,BUY,Filled
224,0.082284,2018-02-28 00:16:15,0.410,0.41,0.082276,ETHBTC,0.033737,SELL,Filled
269,0.082752,2018-02-27 11:00:23,0.410,0.41,0.082756,ETHBTC,0.033929,BUY,Filled
272,0.0,2018-02-27 10:54:57,0.000,0.41,0.082716,ETHBTC,0.000000,BUY,Expired
273,0.0,2018-02-27 10:49:39,0.000,0.409,0.082701,ETHBTC,0.000000,BUY,Expired
310,0.0845,2018-02-27 01:33:38,0.408,0.408,0.0845,ETHBTC,0.034476,SELL,Filled
367,0.086109,2018-02-26 13:26:59,0.408,0.408,0.08612,ETHBTC,0.035133,BUY,Filled
370,0.0,2018-02-26 13:24:58,0.000,0.407,0.086138,ETHBTC,0.000000,BUY,Expired
374,0.0,2018-02-26 13:19:36,0.000,0.406,0.086448,ETHBTC,0.000000,BUY,Expired
458,0.088511,2018-02-26 04:52:37,0.302,0.302,0.088458,ETHBTC,0.026731,SELL,Filled
533,0.0,2018-02-25 00:37:03,0.000,0.302,0.086062,ETHBTC,0.000000,SELL,Expired

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
21,0.000868,2018-03-01 19:33:51,29.15,29.15,0.000868,HSRBTC,0.025303,SELL,Filled
122,0.000895,2018-02-28 17:01:22,29.15,29.15,0.000895,HSRBTC,0.026090,BUY,Filled
125,0.0,2018-02-28 16:55:41,0.00,29.05,0.000896,HSRBTC,0.000000,BUY,Expired
234,0.000918,2018-02-27 22:06:18,28.63,28.63,0.000918,HSRBTC,0.026283,SELL,Filled
237,0.0,2018-02-27 22:00:50,0.00,28.63,0.000915,HSRBTC,0.000000,SELL,Expired
330,0.000932,2018-02-26 21:44:35,28.63,28.63,0.000932,HSRBTC,0.026684,BUY,Filled
336,0.0,2018-02-26 21:39:07,0.00,28.57,0.000932,HSRBTC,0.000000,BUY,Expired
455,0.000954,2018-02-26 04:52:59,18.37,18.37,0.000954,HSRBTC,0.017525,SELL,Filled
532,0.0,2018-02-25 00:37:18,0.00,18.37,0.001006,HSRBTC,0.000000,SELL,Expired

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
146,0.34801,2018-02-28 13:02:53,7.18,7.18,0.34801,ICXBNB,2.49872,BUY,Filled
150,0.0,2018-02-28 12:46:04,0.00,7.14,0.34999,ICXBNB,0.00000,BUY,Canceled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
549,0.00018236,2018-02-25 00:35:55,158.0,158.0,0.00018236,IOTABTC,0.028813,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
7,0.019082,2018-03-02 00:36:43,1.80,1.8,0.019084,LTCBTC,0.034348,BUY,Filled
67,0.019486,2018-03-01 06:46:45,1.79,1.79,0.019486,LTCBTC,0.034880,SELL,Filled
175,0.01975,2018-02-28 06:35:57,1.79,1.79,0.019757,LTCBTC,0.035353,BUY,Filled
182,0.0,2018-02-28 06:30:18,0.00,1.79,0.019801,LTCBTC,0.000000,BUY,Expired
239,0.020214,2018-02-27 20:00:43,1.78,1.78,0.020214,LTCBTC,0.035981,SELL,Filled
288,0.020821,2018-02-27 08:26:08,1.78,1.78,0.020823,LTCBTC,0.037062,BUY,Filled
327,0.02128,2018-02-26 21:50:11,1.58,1.58,0.02128,LTCBTC,0.033623,SELL,Filled
474,0.023595,2018-02-26 02:19:57,1.58,1.58,0.023659,LTCBTC,0.037281,BUY,Filled
529,0.02117,2018-02-25 00:37:27,1.76,1.76,0.02117,LTCBTC,0.037260,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
300,0.0018904,2018-02-27 03:50:07,64.55,64.55,0.0018907,LUNBTC,0.122019,BUY,Filled
306,0.0,2018-02-27 03:44:40,0.00,64.52,0.001915,LUNBTC,0.000000,BUY,Expired
309,0.0,2018-02-27 03:28:18,0.00,64.49,0.0019402,LUNBTC,0.000000,BUY,Expired
323,0.0019816,2018-02-26 23:17:32,64.44,64.44,0.0019811,LUNBTC,0.127694,SELL,Filled
386,0.0020595,2018-02-26 11:49:18,64.44,64.44,0.0020594,LUNBTC,0.132708,BUY,Filled
452,0.0021091,2018-02-26 04:53:20,45.84,45.84,0.0021091,LUNBTC,0.096681,SELL,Filled
528,0.0,2018-02-25 00:37:37,0.00,45.84,0.0024457,LUNBTC,0.000000,SELL,Expired

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
525,0.000709,2018-02-25 00:37:45,32.42,32.42,0.000709,MCOBTC,0.022986,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
40,0.011849,2018-03-01 13:27:50,1.77,1.77,0.01185,NEOBTC,0.020973,BUY,Filled
43,0.0,2018-03-01 13:22:06,0.00,1.76,0.011948,NEOBTC,0.000000,BUY,Expired
44,0.012195,2018-03-01 10:47:49,1.74,1.74,0.012194,NEOBTC,0.021218,SELL,Filled
360,0.012833,2018-02-26 14:20:42,1.74,1.74,0.01284,NEOBTC,0.022330,BUY,Filled
383,0.013154,2018-02-26 12:16:16,1.54,1.54,0.013151,NEOBTC,0.020258,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
521,0.001694,2018-02-25 00:38:00,22.75,22.75,0.001693,OMGBTC,0.038539,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
6,0.0,2018-03-02 00:48:56,0.0,597.0,0.00005173,POWRBTC,0.000000,SELL,Expired
105,0.0,2018-02-28 21:30:35,0.0,597.0,0.00005289,POWRBTC,0.000000,SELL,Expired
172,0.00005432,2018-02-28 06:36:47,597.0,597.0,0.00005434,POWRBTC,0.032429,BUY,Filled
251,0.00005585,2018-02-27 19:01:28,589.0,589.0,0.00005583,POWRBTC,0.032896,SELL,Filled
292,0.00005795,2018-02-27 05:28:44,589.0,589.0,0.00005795,POWRBTC,0.034133,BUY,Filled
299,0.0,2018-02-27 04:29:04,0.0,588.0,0.00005799,POWRBTC,0.000000,BUY,Expired
313,0.0000592,2018-02-27 01:18:33,586.0,586.0,0.0000592,POWRBTC,0.034691,SELL,Filled
399,0.00006004,2018-02-26 09:10:02,586.0,586.0,0.00006004,POWRBTC,0.035183,BUY,Filled
428,0.00006132,2018-02-26 04:59:26,398.0,398.0,0.00006132,POWRBTC,0.024405,SELL,Filled
451,0.0,2018-02-26 04:54:00,0.0,398.0,0.00006132,POWRBTC,0.000000,SELL,Expired
520,0.0,2018-02-25 00:38:10,0.0,398.0,0.00005862,POWRBTC,0.000000,SELL,Expired

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
31,0.002412,2018-03-01 18:37:13,16.05,16.05,0.002412,QTUMBTC,0.038713,BUY,Filled
106,0.002466,2018-02-28 19:12:12,15.83,15.83,0.002465,QTUMBTC,0.039037,SELL,Filled
109,0.0,2018-02-28 19:06:20,0.00,15.83,0.002468,QTUMBTC,0.000000,SELL,Expired
110,0.0,2018-02-28 19:00:36,0.00,15.83,0.002468,QTUMBTC,0.000000,SELL,Expired
195,0.002515,2018-02-28 05:35:49,15.83,15.83,0.002516,QTUMBTC,0.039813,BUY,Filled
198,0.0,2018-02-28 05:30:14,0.00,15.8,0.00252,QTUMBTC,0.000000,BUY,Expired
202,0.0,2018-02-28 05:24:38,0.00,15.78,0.002524,QTUMBTC,0.000000,BUY,Expired
203,0.0,2018-02-28 05:19:08,0.00,15.75,0.002526,QTUMBTC,0.000000,BUY,Expired
420,0.002583,2018-02-26 05:03:27,11.64,11.64,0.002583,QTUMBTC,0.030067,SELL,Filled
427,0.0,2018-02-26 04:59:35,0.00,11.64,0.002588,QTUMBTC,0.000000,SELL,Expired
450,0.0,2018-02-26 04:54:10,0.00,11.64,0.002593,QTUMBTC,0.000000,SELL,Expired
519,0.0,2018-02-25 00:38:20,0.00,11.64,0.002581,QTUMBTC,0.000000,SELL,Expired

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
27,0.00025248,2018-03-01 18:43:03,121.0,121.0,0.0002526,RDNBTC,0.030550,BUY,Filled
30,0.0,2018-03-01 18:37:23,0.0,120.0,0.00025419,RDNBTC,0.000000,BUY,Expired
34,0.0,2018-03-01 18:31:38,0.0,120.0,0.00025393,RDNBTC,0.000000,BUY,Expired
35,0.0,2018-03-01 18:25:58,0.0,120.0,0.00025357,RDNBTC,0.000000,BUY,Expired
36,0.0,2018-03-01 18:20:10,0.0,119.0,0.00025359,RDNBTC,0.000000,BUY,Expired
89,0.0002594,2018-03-01 00:49:21,118.0,118.0,0.00025939,RDNBTC,0.030609,SELL,Filled
221,0.00028529,2018-02-28 00:34:21,118.0,118.0,0.00028529,RDNBTC,0.033664,BUY,Filled
274,0.00029143,2018-02-27 10:23:26,117.0,117.0,0.00029143,RDNBTC,0.034097,SELL,Filled
277,0.0,2018-02-27 10:17:18,0.0,117.0,0.00029197,RDNBTC,0.000000,SELL,Expired
392,0.0003038,2018-02-26 11:11:11,117.0,117.0,0.00030388,RDNBTC,0.035545,BUY,Filled
447,0.00031231,2018-02-26 04:54:23,97.0,97.0,0.00031227,RDNBTC,0.030294,SELL,Filled
518,0.0,2018-02-25 00:38:28,0.0,97.0,0.00032538,RDNBTC,0.000000,SELL,Expired

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
74,0.0,2018-03-01 03:31:06,0.0,699.0,0.00002715,REQBTC,0.000000,SELL,Expired
261,0.00002831,2018-02-27 15:12:52,699.0,699.0,0.00002831,REQBTC,0.019789,BUY,Filled
320,0.00002902,2018-02-26 23:47:37,652.0,652.0,0.00002902,REQBTC,0.018921,SELL,Filled
380,0.00003068,2018-02-26 12:29:42,652.0,652.0,0.00003068,REQBTC,0.020003,BUY,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
53,0.00001439,2018-03-01 08:08:20,1157.0,1157.0,0.0000144,SNTBTC,0.016649,BUY,Filled
57,0.0,2018-03-01 08:04:37,0.0,1151.0,0.00001442,SNTBTC,0.000000,BUY,Expired
58,0.0,2018-03-01 07:53:05,0.0,1144.0,0.00001447,SNTBTC,0.000000,BUY,Expired
59,0.0,2018-03-01 07:24:35,0.0,1138.0,0.00001444,SNTBTC,0.000000,BUY,Expired
60,0.0,2018-03-01 07:18:55,0.0,1132.0,0.00001447,SNTBTC,0.000000,BUY,Expired
73,0.0,2018-03-01 06:08:11,0.0,1126.0,0.00001445,SNTBTC,0.000000,BUY,Expired
83,0.00001477,2018-03-01 02:21:49,1080.0,1080.0,0.00001477,SNTBTC,0.015952,SELL,Filled
104,0.0,2018-02-28 23:01:12,0.0,1080.0,0.00001513,SNTBTC,0.000000,SELL,Expired
169,0.00001542,2018-02-28 06:37:16,1080.0,2270.0,0.00001542,SNTBTC,0.016654,BUY,Partial Fill
514,0.00001687,2018-02-25 00:38:37,1208.0,1208.0,0.00001687,SNTBTC,0.020379,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
75,0.000696,2018-03-01 03:12:33,57.69,57.69,0.000696,STRATBTC,0.040137,BUY,Filled
79,0.0,2018-03-01 02:27:36,0.00,57.57,0.000697,STRATBTC,0.000000,BUY,Expired
135,0.000712,2018-02-28 15:54:12,57.20,57.2,0.000712,STRATBTC,0.040727,SELL,Filled
389,0.000728,2018-02-26 11:11:30,57.20,57.2,0.000728,STRATBTC,0.041642,BUY,Filled
444,0.000743,2018-02-26 04:54:41,36.06,36.06,0.000743,STRATBTC,0.026793,SELL,Filled
513,0.0,2018-02-25 00:38:46,0.00,36.06,0.000733,STRATBTC,0.000000,SELL,Expired

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
210,0.00005174,2018-02-28 05:07:30,87.0,387.0,0.00005174,SUBBTC,0.004501,BUY,Partial Fill
510,0.00005298,2018-02-25 00:38:54,412.0,412.0,0.00005298,SUBBTC,0.021828,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
281,0.00000396,2018-02-27 09:18:08,45103.0,45103.0,0.00000396,TRXBTC,0.178608,BUY,Filled
337,0.00000405,2018-02-26 21:31:52,45077.0,45077.0,0.00000405,TRXBTC,0.182562,SELL,Filled
377,0.00000407,2018-02-26 12:56:43,45077.0,45077.0,0.00000407,TRXBTC,0.183463,BUY,Filled
405,0.00000416,2018-02-26 05:35:48,24476.0,24476.0,0.00000416,TRXBTC,0.101820,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
95,0.0004394,2018-03-01 00:33:32,63.0,63.0,0.00043939,VENBTC,0.027682,SELL,Filled
152,0.00047523,2018-02-28 06:48:38,63.0,63.0,0.00047523,VENBTC,0.029939,BUY,Filled
157,0.0,2018-02-28 06:43:15,0.0,63.0,0.00047711,VENBTC,0.000000,BUY,Expired
168,0.0,2018-02-28 06:37:45,0.0,63.0,0.00047647,VENBTC,0.000000,BUY,Expired
181,0.0,2018-02-28 06:31:56,0.0,62.0,0.00047648,VENBTC,0.000000,BUY,Expired
183,0.0,2018-02-28 06:21:04,0.0,62.0,0.00048003,VENBTC,0.000000,BUY,Expired
242,0.00049012,2018-02-27 19:51:49,61.0,61.0,0.00049007,VENBTC,0.029897,SELL,Filled
245,0.0,2018-02-27 19:46:18,0.0,61.0,0.00048799,VENBTC,0.000000,SELL,Expired
333,0.0005345,2018-02-26 21:41:08,61.0,61.0,0.0005345,VENBTC,0.032605,BUY,Filled
346,0.00054778,2018-02-26 20:46:24,55.0,55.0,0.000547,VENBTC,0.030128,SELL,Filled
477,0.00059867,2018-02-25 15:45:55,55.0,55.0,0.00059994,VENBTC,0.032927,BUY,Filled
484,0.00061279,2018-02-25 14:25:13,54.0,54.0,0.0006126,VENBTC,0.033090,SELL,Filled
488,0.00061499,2018-02-25 14:20:17,54.0,54.0,0.00061654,VENBTC,0.033209,BUY,Filled
507,0.000574,2018-02-25 00:39:02,58.0,58.0,0.000574,VENBTC,0.033292,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
92,0.00003676,2018-03-01 00:45:46,499.0,499.0,0.00003676,VIBEBTC,0.018343,BUY,Filled
178,0.00003755,2018-02-28 06:33:16,461.0,461.0,0.00003753,VIBEBTC,0.017311,SELL,Filled
194,0.0,2018-02-28 05:43:22,0.0,461.0,0.00003929,VIBEBTC,0.000000,SELL,Expired
268,0.0,2018-02-27 12:24:39,0.0,461.0,0.00004032,VIBEBTC,0.000000,SELL,Expired
326,0.0,2018-02-26 22:47:29,0.0,461.0,0.0000413,VIBEBTC,0.000000,SELL,Expired
395,0.00004334,2018-02-26 09:23:01,461.0,461.0,0.00004334,VIBEBTC,0.019980,BUY,Filled
491,0.0,2018-02-25 02:04:19,0.0,936.0,0.00004235,VIBEBTC,0.000000,BUY,Expired
492,0.00004337,2018-02-25 00:40:12,914.0,914.0,0.00004336,VIBEBTC,0.039640,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
187,0.000597,2018-02-28 06:04:49,58.63,58.63,0.000597,WAVESBTC,0.034996,BUY,Filled
504,0.000674,2018-02-25 00:39:12,19.34,19.34,0.000674,WAVESBTC,0.013035,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
24,0.0017244,2018-03-01 19:01:29,11.45,11.45,0.0017244,WTCBTC,0.019744,BUY,Filled
61,0.0017733,2018-03-01 07:07:06,9.94,9.94,0.0017732,WTCBTC,0.017626,SELL,Filled
207,0.0020115,2018-02-28 05:08:00,9.94,9.94,0.0020115,WTCBTC,0.019994,BUY,Filled
501,0.0021759,2018-02-25 00:39:20,6.71,6.71,0.0021758,WTCBTC,0.014600,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
0,0.00003049,2018-03-02 00:56:15,1154.0,1154.0,0.00003049,XLMBTC,0.035185,BUY,Filled
5,0.0,2018-03-02 00:50:32,0.0,1151.0,0.00003047,XLMBTC,0.000000,BUY,Expired
48,0.00003115,2018-03-01 10:20:59,1139.0,1139.0,0.00003114,XLMBTC,0.035477,SELL,Filled
52,0.0,2018-03-01 10:15:19,0.0,1139.0,0.00003103,XLMBTC,0.000000,SELL,Expired
199,0.00003267,2018-02-28 05:25:53,1139.0,1139.0,0.00003267,XLMBTC,0.037211,BUY,Filled
254,0.00003338,2018-02-27 18:04:11,1134.0,1134.0,0.00003338,XLMBTC,0.037853,SELL,Filled
353,0.00003495,2018-02-26 19:08:36,1134.0,1134.0,0.00003495,XLMBTC,0.039633,BUY,Filled
441,0.00003568,2018-02-26 04:55:32,873.0,873.0,0.00003568,XLMBTC,0.031149,SELL,Filled
500,0.0,2018-02-25 00:39:28,0.0,873.0,0.00003523,XLMBTC,0.000000,SELL,Expired

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
151,0.0,2018-02-28 10:45:11,0.000,0.704,0.027582,XMRBTC,0.00,SELL,Expired
238,0.0,2018-02-27 21:19:18,0.000,0.704,0.02817,XMRBTC,0.00,SELL,Expired
436,0.028408,2018-02-26 04:55:42,0.704,0.704,0.028408,XMRBTC,0.02,BUY,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
204,0.00008575,2018-02-28 05:16:05,389.0,389.0,0.00008575,XRPBTC,0.033357,BUY,Filled
258,0.00008768,2018-02-27 17:30:46,388.0,388.0,0.00008768,XRPBTC,0.034020,SELL,Filled
356,0.00009073,2018-02-26 16:15:14,388.0,388.0,0.00009073,XRPBTC,0.035202,BUY,Filled
433,0.0000928,2018-02-26 04:55:55,286.0,286.0,0.0000928,XRPBTC,0.026541,SELL,Filled
499,0.0,2018-02-25 00:39:45,0.0,286.0,0.00009312,XRPBTC,0.000000,SELL,Expired

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
98,0.00000517,2018-03-01 00:23:12,6729.0,6729.0,0.00000517,XVGBTC,0.034776,BUY,Filled
102,0.0,2018-03-01 00:17:42,0.0,6712.0,0.00000517,XVGBTC,0.000000,BUY,Expired
111,0.00000529,2018-02-28 18:50:52,6352.0,6352.0,0.00000529,XVGBTC,0.033602,SELL,Filled
162,0.00000551,2018-02-28 06:38:43,6352.0,6352.0,0.00000551,XVGBTC,0.035000,BUY,Filled
496,0.00000589,2018-02-25 00:39:53,4878.0,4878.0,0.00000589,XVGBTC,0.028731,SELL,Filled

,Avg Trading Price,Date,Filled,Order Amount,Order Price,Pair,Total,Type,status
4,0.0,2018-03-02 00:51:10,0.000,0.908,0.036145,ZECBTC,0.000000,BUY,Expired
140,0.03689,2018-02-28 15:15:20,0.892,0.892,0.03689,ZECBTC,0.032906,SELL,Filled
231,0.038205,2018-02-27 23:41:43,0.892,0.892,0.038204,ZECBTC,0.034078,BUY,Filled
246,0.0,2018-02-27 19:30:57,0.000,0.89,0.038211,ZECBTC,0.000000,BUY,Expired
284,0.039002,2018-02-27 08:50:39,0.886,0.886,0.039001,ZECBTC,0.034555,SELL,Filled
287,0.0,2018-02-27 08:45:16,0.000,0.886,0.039125,ZECBTC,0.000000,SELL,Expired
363,0.039842,2018-02-26 14:12:31,0.886,0.886,0.039842,ZECBTC,0.035301,BUY,Filled
366,0.0,2018-02-26 14:07:23,0.000,0.885,0.039866,ZECBTC,0.000000,BUY,Expired
411,0.040703,2018-02-26 05:16:54,0.634,0.634,0.040703,ZECBTC,0.025806,SELL,Filled
415,0.0,2018-02-26 05:10:41,0.000,0.634,0.04072,ZECBTC,0.000000,SELL,Expired
419,0.0,2018-02-26 05:05:27,0.000,0.634,0.04072,ZECBTC,0.000000,SELL,Expired
432,0.0,2018-02-26 04:56:13,0.000,0.634,0.040772,ZECBTC,0.000000,SELL,Expired
495,0.0,2018-02-25 00:40:02,0.000,0.634,0.039959,ZECBTC,0.000000,SELL,Expired